package sites

import (
	"errors"
	"fmt"
	"strings"
)

// Directives copied verbatim from the original server blocks so the
// maintenance vhost binds the same addresses and terminates TLS with the
// same certificates. Everything else is dropped; `nginx -t` guards the
// result before it goes live.
var copiedDirectives = map[string]bool{
	"listen":               true,
	"server_name":          true,
	"ssl_certificate":      true,
	"ssl_certificate_key":  true,
	"ssl_password_file":    true,
	"ssl_reject_handshake": true,
	"http2":                true,
	"http3":                true,
}

// GenerateMaintenanceVhost builds a 503 vhost from a site config: one
// server block per original server block, reusing its bind/TLS setup and
// serving <stateDir>/maintenance.html for every request.
func GenerateMaintenanceVhost(src, stateDir string) (string, error) {
	blocks := extractServerBlocks(src)
	if len(blocks) == 0 {
		return "", errors.New("no server block found in site config")
	}
	var b strings.Builder
	b.WriteString("# Generated by lightngx maintenance mode. Do not edit.\n")
	for _, directives := range blocks {
		b.WriteString("server {\n")
		for _, d := range directives {
			fmt.Fprintf(&b, "    %s;\n", strings.Join(d, " "))
		}
		fmt.Fprintf(&b, "    root %q;\n", stateDir)
		b.WriteString("    error_page 503 /maintenance.html;\n")
		b.WriteString("    add_header Retry-After 300 always;\n")
		b.WriteString("    location = /maintenance.html {\n        internal;\n    }\n")
		b.WriteString("    location / {\n        return 503;\n    }\n")
		b.WriteString("}\n")
	}
	return b.String(), nil
}

type token struct {
	kind byte // 'w' word, ';', '{', '}'
	text string
}

// lex tokenizes nginx config syntax: words (with quote support), block
// delimiters and directive terminators. Comments run to end of line.
func lex(src string) []token {
	var out []token
	i := 0
	for i < len(src) {
		c := src[i]
		switch {
		case c == ' ' || c == '\t' || c == '\r' || c == '\n':
			i++
		case c == '#':
			for i < len(src) && src[i] != '\n' {
				i++
			}
		case c == ';' || c == '{' || c == '}':
			out = append(out, token{kind: c})
			i++
		case c == '"' || c == '\'':
			quote := c
			j := i + 1
			for j < len(src) {
				if src[j] == '\\' && j+1 < len(src) {
					j += 2
					continue
				}
				if src[j] == quote {
					break
				}
				j++
			}
			if j < len(src) {
				j++
			}
			out = append(out, token{kind: 'w', text: src[i:j]})
			i = j
		default:
			j := i
			for j < len(src) && !strings.ContainsRune(" \t\r\n;{}#", rune(src[j])) {
				j++
			}
			out = append(out, token{kind: 'w', text: src[i:j]})
			i = j
		}
	}
	return out
}

// extractServerBlocks returns, for each top-level server block, the
// directives (token texts) we copy into the maintenance vhost.
func extractServerBlocks(src string) [][][]string {
	tokens := lex(src)
	var blocks [][][]string
	depth := 0
	i := 0
	for i < len(tokens) {
		t := tokens[i]
		if depth == 0 && t.kind == 'w' && t.text == "server" && i+1 < len(tokens) && tokens[i+1].kind == '{' {
			i += 2
			blocks = append(blocks, captureServer(tokens, &i))
			continue
		}
		switch t.kind {
		case '{':
			depth++
		case '}':
			if depth > 0 {
				depth--
			}
		}
		i++
	}
	return blocks
}

// captureServer scans one server block (starting just after its `{`) and
// collects the copied directives found at server level. *i is advanced
// past the closing `}`.
func captureServer(tokens []token, i *int) [][]string {
	var directives [][]string
	var current []string
	depth := 0
	for *i < len(tokens) {
		t := tokens[*i]
		*i++
		switch t.kind {
		case 'w':
			if depth == 0 {
				current = append(current, t.text)
			}
		case ';':
			if depth == 0 && len(current) > 0 {
				if copiedDirectives[current[0]] {
					directives = append(directives, current)
				}
				current = nil
			}
		case '{':
			depth++
			current = nil
		case '}':
			if depth == 0 {
				return directives
			}
			depth--
		}
	}
	return directives
}
